{
  "functions": {
    "create-checkout-session": {
      "verify_jwt": false
    },
    "stripe-webhook": {
      "verify_jwt": false
    },
    "read-case": {
      "verify_jwt": false
    },
    "doc-extract-start": {
      "verify_jwt": false
    },
    "save-case": {
      "verify_jwt": false
    },
    "test-doc-extract": {
      "verify_jwt": false
    }
  }
}
