{
  "functions": {
    "create-checkout-session": {
      "verify_jwt": false
    },
    "stripe-webhook": {
      "verify_jwt": false
    },
    "read-case": {
      "verify_jwt": false
    }
  }
}

